language: cpp
compiler: gcc

jobs:
  include:
    # Build and test on Linux.
    - stage: "Build and Test on Linux"
      name: "Build and Test on Linux"
      script:
        - sudo cp compile.sh.example compile.sh
        - sudo chmod 0700 compile.sh
        - sudo ./compile.sh
        - sudo cp main tests/main
        - sudo cp data tests/data -r -f
        - cd tests
        - sudo chmod 0700 test.sh
        - sudo ./test.sh
      os: linux
      dist: bionic

    # Build and test on Windows.
    - stage: "Build and Test on Windows"
      name: "Build and Test on Windows"
      script:
        - cp compile.sh.example compile.sh
        - chmod 0700 compile.sh
        - ./compile.sh
        - cp main tests/main
        - cp data tests/data -r -f
        - cd tests
        - chmod 0700 test.sh
        - ./test.sh
      os: windows