language: cpp
compiler: gcc
    
os: linux
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-7
    
before_script:
    - export CC=gcc-7
    - export CXX=g++-7
    - eval "CC=gcc-7 && GXX=g++-7"    
    
script:
    - sudo cp compile.sh.example compile.sh
    - sudo chmod 0700 compile.sh
    - sudo ./compile.sh