name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest']

    steps:
    - uses: actions/checkout@v2
      name: Checkout repository

    - name: make
      run: make

    - name: make - copy test into testing folder
      run: make init_test

    - name: make - test
      run: make test

    - name: Upload artifacts (pushes only)
      uses: actions/upload-artifact@v2
      with:
        name: build-executable
        path: |
          data/
          main
          main.exe
        if-no-files-found: error
      if: ${{ github.event_name == 'push' }}

    - name: cleaning afterworks
      run: make clean

  create-release:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Download artifacts from previous build
        uses: actions/download-artifact@v2
        with:
          name: build-executable

      - name: Zipping release artifact
        uses: vimtor/action-zip@v1
        with:
          files: data/ main main.exe
          recursive: false
          dest: release.zip
      
      - name: Drafting a new release.
        uses: release-drafter/release-drafter@v5
        id: draft-new-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.draft-new-release.outputs.upload_url }}
          asset_path: release.zip
          asset_name: release.zip
          asset_content_type: application/zip
