name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linter:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: clang-format linter
        run: make lint

  build-and-test:
    needs: linter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout repository

    - name: make
      run: make

    - name: make - copy test into testing folder
      run: make init_test

    - name: make - test_silent
      # Running silent (without progress check)
      run: make test_silent

    - name: cleaning afterworks
      run: make clean
