name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  linter:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: clang-format linter
        run: make lint

  build-and-test:
    needs: linter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout repository

    - name: make
      run: make
      if: ${{ github.event_name == 'push' }}

    - name: make (with test coverage)
      run: make gcov
      if: ${{ github.event_name == 'pull_request_target' }}

    - name: make - copy test into testing folder
      run: make init_test

    - name: make - test
      run: make test

    - name: make - init code coverage
      run: |
        sudo apt-get install -y lcov && make lcov
      if: ${{ github.event_name == 'pull_request_target' }}

    - name: upload code coverage report
      uses: zgosalvez/github-actions-report-lcov@v1
      with:
        coverage-files: coverage.info
        minimum-coverage: 80
        artifact-name: code-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ github.event_name == 'pull_request_target' }}

    - name: cleaning afterworks
      run: make clean
