name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest']

    steps:
    - uses: actions/checkout@v2
      name: Checkout repository

    - name: make
      run: make

    - name: make - copy test into testing folder
      run: make init_test

    - name: make - test
      run: make test

    - name: Upload artifacts (pushes only)
      uses: actions/upload-artifact@v2
      with:
        name: build-executable
        path: |
          data/
          main
          main.exe
          LICENSE
      if: ${{ github.event_name == 'push' }}

    - name: cleaning afterworks
      run: make clean

  create-release:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts from previous build
        uses: actions/download-artifact@v2
        with:
          name: build-executable
    
      - name: Zipping release artifact
        uses: vimtor/action-zip@v1
        with:
          files: |
            main
            main.exe
            data/
            LICENSE
          recursive: true
          dest: release.zip

      - name: Create release with artifacts
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          automatic_release_tag: 'latest'
          title: 'Latest Build'
          files: release.zip
