name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make copy test into testing folder
      run: make init_test
    - name: make test
      run: make test
    - name: cleaning afterworks
      run: make clean
